// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { Toaster } from "@/components/ui/sonner";
import { UiProvider } from "@/contexts/UiContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EConex Group - Serviços Completos Angola",
  description:
    "Serviços de limpeza, manutenção, climatização, automóvel e piscinas em Angola. Soluções profissionais com atendimento 24/7.",
  // ✅ Usa o favicon gerido pelo Next em src/app/icon.svg
  // (Evita conflito com PNG e elimina o erro do loader)
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />

        {/* ✅ Favicon correto (SVG) */}
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UiProvider>
          {children}
          <Toaster />
        </UiProvider>
      </body>
    </html>
  );
}
