// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import type React from "react";
import { Inter, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { UiProvider } from "@/contexts/UiContext";

/**
 * Fonte principal do site: Inter
 * Mantive a variável "--font-geist-sans" para NÃO quebrares nada no CSS existente.
 */
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "EConex Group - Serviços Completos Angola",
  description:
    "Serviços de limpeza, manutenção, climatização, automóvel e piscinas em Angola. Soluções profissionais com atendimento 24/7.",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="/icon.svg" type="image/svg+xml" />
      </head>

      <body className={`${inter.variable} ${geistMono.variable} antialiased`}>
        <UiProvider>
          {children}
          <Toaster />
        </UiProvider>
      </body>
    </html>
  );
}
